### PR TITLE
[Feat]: ⭐ New component - ScratchToReveal

### PR DESCRIPTION
**Pull request by dipeshtamang07**
**Summary**

The ScratchToReveal component adds an interactive scratch-off effect to reveal hidden content. It supports customizable cursor size, fixed dimensions, and completion animations using Framer Motion, making it perfect for promotions, hidden messages, or game elements.

**Features**

1. Interactive Scratch-Off Effect: Users can scratch off the overlay to reveal hidden content beneath.
2. Completion Animation: Animates (scale-up, rotate left and right, then back to the initial position) using Framer Motion upon scratch completion.
3. Versatile Content: Supports any children components, including images, text, or HTML content.
4. onComplete (function): Optional callback function triggered when the scratch is complete.

**Props**

1. width (number): Sets the width of the scratchable area.
2. height (number): Sets the height of the scratchable area.
3. minScratchPercentage (number): Minimum percentage of scratched area to be considered as completed (Value between 0 and 100)
4. onComplete (function): Optional callback function triggered when the scratch is complete.
5. className (string): Custom Tailwind CSS classes for additional styling of the container.

**Preview**

[scratch-to-reveal.webm](https://github.com/magicuidesign/magicui/assets/42607820/5c9fb748-a266-4d7b-ab15-1a00ff880950)

### CODE REVIEW

**Comment by dipeshtamang07** [comment]
@dillionverma Please review this

**Comment by Draxx0** [comment]
that's really cool !

**Comment by alamenai** [comment]
Fantastic @dipeshtamang07 ! Curious to try it in one of my projects

**Comment by itsarghyadas** [comment]
This is a really fun and useful component! I’ve reviewed it and made two changes:

- Ensured the animation completes fully before executing the onComplete function.
- Added a new `gradientColors` prop to allow control over the gradients.

**Pull request merged**
