### PR TITLE
fixing #304: The fist component should be Hero Video Dialog after clicking components link #304

### LINKED ISSUE #304: [Doc]: The first component should be Hero Video Dialog after clicking components link
Hi @dillionverma ,

After you added the HVD component, it seems you forgot to target it as the first component when the users click on the components link.

### Current

Marquee

### Expected

Hero Video Dialog

### PR DESCRIPTION
**Pull request by sanjay-mali**
Changed the order of component items to improve layout and usability.

Fixes #304

Before:

https://github.com/user-attachments/assets/30542077-e4e9-4cea-b4f0-ad5c6ac2a537

After : 

https://github.com/user-attachments/assets/00d435f5-1b7e-4a16-af67-046802a8de5f

### CODE REVIEW

**Comment by sanjay-mali** [comment]
Any update?

**Comment by itsarghyadas** [comment]
I have approved the PR here https://github.com/magicuidesign/magicui/pull/322 and I think this is the same topic PR if I am not wrong?

**Comment by sanjay-mali** [comment]
Yes, it's the same branch. When I was working on improving accessibility, I forgot to create a new branch, so everything got mixed up. Apologies for the confusion. You can go ahead and close this PR.

**Comment by itsarghyadas** [comment]
Nice. Thanks for clarifying. I am closing this PR now.

**Pull request closed without merging**
