### PR TITLE
Enhancement: Magic UI CLI, Superset of shadcn-ui

### PR DESCRIPTION
**Pull request by rajatsandeepsen**
# magicui-cli
A CLI for adding magic ui components to your project. Superset of shadcn-ui.

Screenshot 2024-05-26 154458

Enhancement: #49 ✅ 

## Usage

Use the `init` command to initialize dependencies for a new project.

The `init` command installs dependencies (`framer-motion`), adds the `cn` util, configures `tailwind.config.js`, and CSS variables for the project.

```bash
npx magicui-cli init
```

### shadcn-ui project 
If your project is already using the `shadcn-ui`, don't worry! You can still use magicui.

```bash
npx shadcn-ui init
```

Just add these two lines to your `components,json` file and install `framer-motion`
```bash
npm install framer-motion
```
```diff
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "app/globals.css",
    "baseColor": "slate",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
+   "ui": "@/components/ui",
+   "magicui": "@/components/magicui"
  }
}
```

## add

Use the `add` command to add components to your project.

The `add` command adds a component to your project and installs all required dependencies.

```bash
npx magicui-cli add [component]
```

### Example

```bash
npx magicui-cli add bento-grid
```

You can also use the optional `--all` flag to install all components:
```bash
npx magicui-cli add --all
```

You can also use the `--exmaple` flag to select and install example & demo you saw on webside:
```bash
npx magicui-cli add --example
```

You can also run the command without any arguments to view a list of all available components:

```bash
npx magicui-cli add
```

## shadcn-ui

You can also use the same CLI for selecting & installing shadcn-ui components:

```bash
npx magicui-cli add --shadcn button
```
```bash
npx magicui-cli add --shadcn --all
```

## Magic UI Premium Components

If user has the "env", just login the CLI and enjoy the premium components
```bash
npx magicui-cli auth --login <secret-env>
```

Use `--pro` tag to list premium components from [pro webside](https://pro.magicui.design)
```bash
npx magicui-cli add --pro 
```

CLI also supports the premium project templates. It will download the private repo as zip file
```bash
npx magicui-cli project
```

## TODO

1. Update CLI docs
2. Solve org support with team ENV

### CODE REVIEW

**Comment by itsarghyadas** [comment]
Do you have any video recordings of how it works in a real codebase?

**Review by Behnam20176 — APPROVED** [review]

**Comment by rajatsandeepsen** [comment]
> Do you have any video recordings of how it works in a real codebase?

https://github.com/magicuidesign/magicui/assets/93584596/134b7eb7-f849-47d4-ba50-c059e04a66e7

**Comment by rajatsandeepsen** [comment]
### If user is logged in

https://github.com/magicuidesign/magicui/assets/93584596/1a3487de-be45-420d-a277-3c49236fadf1

### if user is not logged in
image

**Comment by rajatsandeepsen** [comment]
### How to login & logout in Magic UI CLI

https://github.com/magicuidesign/magicui/assets/93584596/afb5ade3-5123-4d0c-8001-c55c8a98d35e

**Pull request closed without merging**
