### PR TITLE
Custom Caption Below Number | Update animated-circular-progress-bar.tsx

### PR DESCRIPTION
**Pull request by zandercoffman**
I added a custom caption below the number's location. I also edited the percentage and the text to be in the middle for standard purposes.

### CODE REVIEW

**Review by itsarghyadas — CHANGES_REQUESTED** [review]
What is the actual change?

Can you send me an image or gif about the change?

**Comment by zandercoffman** [comment]
> What is the actual change?
> 
> Can you send me an image or gif about the change?

Screenshot 2024-09-18 174814

It adds a little caption to give a user context about what the number could be correlated with; in the image it shows it when there is a caption, and no caption, and it still is the original design when there is no caption so it does not get in the way 😁

**Comment by itsarghyadas** [comment]
Got it. Is it activated on hover or automatically? Cause when I ran it locally it didn't show me. I will give it a try again and let you know. But it is a good catch. I like it.

**Comment by zandercoffman** [comment]
> Got it. Is it activated on hover or automatically? Cause when I ran it locally it didn't show me. I will give it a try again and let you know. But it is a good catch. I like it.

It is currently only automatically, once you put in the caption, it will show, I can work on another commit that makes it only show on hover

Also, did you do the caption attribute to the component? That is the only way itl show is if the caption attribute exists

And thank you 😊

**Comment by dillionverma** [comment]
Hi @zandercoffman! Thanks for opening a PR for this.

Just reviewed further and decided that this might be valuable for your personal usecase but might not be beneficial to everyone using the library.

Going to close this issue for now.

If you are reading this and there is further demand for something like this to be merged in the core library, please feel free to comment below to explain why

**Pull request closed without merging**
