### PR TITLE
docs: update-installation-by-framework

### PR DESCRIPTION
**Pull request by tomonarifeehan**
First attempt at issue: https://github.com/magicuidesign/magicui/issues/111

Changes Made:
- Created ComponentInstallation which contains React.js, Vue.js, Svelte cards

Screenshot 2024-06-01 at 3 13 16 AM

Screenshot 2024-06-01 at 3 30 33 AM

Screenshot 2024-06-01 at 3 30 38 AM

Screenshot 2024-06-01 at 3 09 57 AM

### CODE REVIEW

**Comment by tomonarifeehan** [comment]
@dillionverma not exactly sure which files I need to touch to allow for MDX navigation

I added to items[] in **docs.ts** and created **installation** folder and added files **next.mdx**, **vue.mdx**, **svelte.mdx** for now

Screenshot 2024-06-01 at 2 58 18 AM

Screenshot 2024-06-01 at 2 59 41 AM

**Comment by safethecode** [comment]
@tomonarifeehan ⚡️
Question:
**This looks like a good PR! 🔥**
However, how about matching the style to something like 'https://ui.shadcn.com/docs/installation'?
It seems the styles don't match right now, like center alignment and so on.

**Comment by tomonarifeehan** [comment]
> However, how about matching the style to something like 'https://ui.shadcn.com/docs/installation'?

dude i literally copied-pasted from shadcn

**Comment by dillionverma** [comment]
the slight styling differences is because we use tailwindcss-typography in our markdown styling wheras shadcn does not

i just added the not-prose class here for now as a temp fix

we should sort out later on if we should stick with tailwind markdown styles or roll our own 

image

**Review by dillionverma — APPROVED** [review]
TYSM LFG 🔥

**Pull request merged**
