### PR TITLE
fix(docs): adjust the height for the docs to start from the beginning

### PR DESCRIPTION
**Pull request by Joshyahweh**
The documentation was not starting from the beginning, this PR fixes that by taking the height into consideration.

### CODE REVIEW

**Comment by itsarghyadas** [comment]
Is this still an issue @Joshyahweh ?

If it is, can you quickly show me a screenshot or a small recording of the issue so I can understand it quickly.

Thank you.

**Comment by itsarghyadas** [comment]
Since I haven't received any feedback on what this is supposed to solve, and based on my personal testing of the documentation, I don't see any issues with the height at this time. Therefore, I am closing this PR for now.

**Comment by Joshyahweh** [comment]
Hi, I just saw your email, here is the screenshot of the issue, the
site does not start from the beginning. A part is being cut off.

**Comment by Joshyahweh** [comment]
If it can be reopened, that would be great because it was solved in the PR

**Pull request closed without merging**
