### PR TITLE
feat: update text reveal component

### PR DESCRIPTION
**Pull request by ZiJson**
I have been using MagicUI for a while, and I love its clean design and fancy effects. However, when I use the Text Reveal component, it seems to be less flexible, so I couldn't help modifying it. I hope these changes help.

The major changes are:

- You can now wrap children elements inside.
- Customizable sticky content height, instead of being limited to full screen height.
- Customizable animation position for the text, rather than only having it centered.

https://github.com/user-attachments/assets/96e5145f-8a98-415e-bad7-0f2ff1c2b807

### CODE REVIEW

**Comment by itsarghyadas** [comment]
@ZiJson Thank you for enhancing the component with support for child elements.

However, the other improvements:
- Customizable sticky content height, instead of being limited to full screen height.
- Customizable animation position for the text, rather than only having it centered.

Could you clarify the purpose of the additional props and the initial issue that led to these changes?

**Comment by ZiJson** [comment]
@itsarghyadas thanks for reply

I realized I initially made the component too complex, which made it hard to balance flexibility with ease of use. I've simplified my changes, keeping only the most useful parts:

- **Support for child elements**
- **Customizable line breaks**
prevents text from overlapping with child elements, allowing for more design options.
 - **Option to choose text alignment**
also helps avoid overlapping with child elements.

**Comment by itsarghyadas** [comment]
Thanks for the reply. I will check it as soon as I get some time and will get back to you.

**Comment by ZiJson** [comment]
Example:

image

code:

``` jsx
      <TextReveal
        text={["Magic UI", "will change the way", "you design."]}
        side="left"
      >
        <div className="flex size-full items-center justify-center">
          <Ripple />
        </div>
      </TextReveal>

**Comment by itsarghyadas** [comment]
Hey @ZiJson, I’ve reviewed the code, and as we discussed, we don’t want to add any additional complexity or props to this component for now. It works as we intended, so we’ll close this PR. In the future, if we decide we need this functionality, we can revisit and discuss. Thank you for your contribution!

**Pull request closed without merging**
