### PR TITLE
Feat:Add Support for Profile Links in AvatarCircles Component

### LINKED ISSUE #305: [Avatar Circles]: Add urls ( links ) for each avatar
**Is your feature request related to a problem? Please describe.**

I used this component in [rehook.dev](https://www.rehook.dev/) to link each avatar to the related Github profile but no prop allowed me to do that

**Describe the solution you'd like**
The `avatarUrls` could be an array of objects that contains the URL for the image and another URL ( link ) for the profile.

### PR DESCRIPTION
**Pull request by sanjay-mali**
fix #305

### Changes Made
- Updated AvatarCircles Component:
   - Modified the AvatarCircles component to support profile URLs.
   - Added a new avatarUrls prop that now accepts an array of objects, each containing an imageUrl and profileUrl
  
### Usage
To utilize this feature, update the avatarUrls prop with an array of objects, where each object includes:
- imageUrl: The URL of the avatar image.
- profileUrl: The URL of the corresponding GitHub profile.

### CODE REVIEW

**Comment by sanjay-mali** [comment]
Any update?

**Comment by itsarghyadas** [comment]
@sanjay-mali  Are you addressing two different issues here? Any changes made to the `hero-video-dialog` component should be in a separate PR, as it should address a different issue, right? I understand the changes made for Avatar, but could you clarify what changes you're making to the `hero-video-dialog` component?

**Comment by sanjay-mali** [comment]
@itsarghyadas Yes, you are correct that changes to the hero-video-dialog component should ideally be in a separate PR. However, in this particular PR, the changes to hero-video-dialog are as follows:

Dynamic Gradient Background- I added functionality to allow dynamic background gradients based on the startColor and endColor props. Previously, the component only used a fixed gradient (from-primary/30 to-primary). Now, it checks whether the provided colors are valid Tailwind colors or custom ones and applies them accordingly.

I hope that clarifies the changes. Let me know if you'd like me to split this into a separate PR or if you need further refinements.

**Comment by sanjay-mali** [comment]
@dillionverma Thank you! I completely understand. I'll go ahead and create a separate PR for the changes to the hero-video-dialog component so it's easier to review and merge. I'll get that done shortly! 😊

Let me know if there's anything else I can assist with!

**Comment by sanjay-mali** [comment]
Hey @dillionverma , I created a separate PR as you suggested. Please check #417 and let me know if the changes look good. Should we go ahead and close this PR?

**Comment by itsarghyadas** [comment]
@sanjay-mali I’m reviewing that right now. Thanks for the extra work! You can close this PR and create or update this one for your proposed changes to the `hero-video-dialog` component.

**Comment by sanjay-mali** [comment]
@itsarghyadas Thank you 😊

**Pull request closed without merging**
