### PR TITLE
Added Background Light Component to Magic UI. 

### PR DESCRIPTION
**Pull request by Gitstar-OC**
This commit solves the problem of addition of extra file package-lock.json file in this pull request. #349.

### CODE REVIEW

**Comment by Gitstar-OC** [comment]
Why is this pull request not being accepted ?

**Comment by Gitstar-OC** [comment]
This repository is no longer active!! Fix this.

**Comment by Gitstar-OC** [comment]
Will this be merged ? Please merege it!!

**Comment by itsarghyadas** [comment]
@Gitstar-OC Could you explain what this component's usecase? Additionally, could you share a short video demonstrating how the component works?

**Comment by Gitstar-OC** [comment]
@itsarghyadas #340 shows how it looks and it's usage.

**Comment by itsarghyadas** [comment]
Unfortunately, when I tested your code locally, it didn't cover the entire background as expected. I assumed it would fill the whole area, but instead, it only displays a background behind the text, not spanning the full height and width.

**Comment by Gitstar-OC** [comment]
Wait, I think some style adjustments will solve that, I will work on it and update this with a new commit tomorrow.

**Comment by Gitstar-OC** [comment]
Hey just as an update, I have worked on it but I am unable to see the component on the link after following all of the steps but my component is still not visible and shows not found.

**Comment by itsarghyadas** [comment]
Yeah I guess its because `<ComponentPreview name="backgroun-light-demo` it should be `backgroun-light-demo`, check the spelling

**Comment by Gitstar-OC** [comment]
I  tried changing that but the whole thing is not visible, if there is an error in the component the name and other deatils should still appear but it is not the case.

**Comment by itsarghyadas** [comment]
Hey, I checked it again and found that it doesn’t work as described in https://github.com/magicuidesign/magicui/issues/340 

For now, we’re closing this PR. If you come up with a fix, you’re welcome to create another PR, and we’ll be happy to review it. Thank you!

**Pull request closed without merging**
