### PR TITLE
[Docs] Update contributing guide

### PR DESCRIPTION
**Pull request by BankkRoll**
Add more info on the 5 files to change when contributing

### CODE REVIEW

**Review by unnamed-lab — APPROVED** [review]
I would love to commend this newly formatted Contribution markdown. I believe it's easier to understand, self-explanatory and won't request new contributors to switch through pages, especially when setting up the component files.

**Review by dillionverma — APPROVED** [review]
EXTREMELY WELL WRITTEN TYSM  🔥

**Comment by dillionverma** [comment]
this gonna help a lot of newcomers

**Comment by unnamed-lab** [comment]
> this gonna help a lot of newcomers

It sure will 💯

**Pull request merged**
