### PR TITLE
feat: wavy-dot-pattern

### PR DESCRIPTION
**Pull request by tomonarifeehan**
Feature: A background dot pattern that ripples when dots are clicked.

https://github.com/magicuidesign/magicui/assets/20110627/9fe65516-1e90-4364-b6fe-2af8444ab4ac

### CODE REVIEW

**Comment by dillionverma** [comment]
very cool animation!

I have some feedback to improve it

I notice when I click on it once, and then twice, the first wave gets frozen and it looks a bit awkward.

Do you have any ideas to make that one part look less awkward?

https://github.com/magicuidesign/magicui/assets/16860528/7a81c2f2-9878-48cd-a53e-f2f8f9ffc923

**Comment by tomonarifeehan** [comment]
> Do you have any ideas to make that one part look less awkward?

I have no ideas right now. I'll look into it.

**Comment by tomonarifeehan** [comment]
> I notice when I click on it once, and then twice, the first wave gets frozen and it looks a bit awkward.

Added setTimeout disable click for 2000ms and then allow again.

https://github.com/magicuidesign/magicui/pull/62/commits/2e423055358ce52c474ee0922fb44d5ff9adff18

**Comment by tomonarifeehan** [comment]
accidentally deleted branch lol

**Comment by dillionverma** [comment]
haha all good ill take a look at it again 👀

**Review by dillionverma — APPROVED** [review]
tysm for adding this 🙏

**Pull request merged**
