### PR TITLE
feat: letter-pullup

### PR DESCRIPTION
**Pull request by tomonarifeehan**
Feature: Staggered Letter Pullup Text Animation

Pulled from issues: https://github.com/magicuidesign/magicui/issues/19

https://github.com/magicuidesign/magicui/assets/20110627/b9ea2c26-e694-44bc-a5da-a7f049e41389

### CODE REVIEW

**Review by dillionverma — APPROVED** [review]
LGTM TYSM 🔥🔥🔥🔥

**Comment by dillionverma** [comment]
once you fix merge conflict ill merge it in

**Comment by tomonarifeehan** [comment]
Fixed merge conflict.

**Comment by dillionverma** [comment]
TYSMMMMM

**Pull request merged**
