### PR TITLE
refactor: optimize AnimatedList component

### PR DESCRIPTION
**Pull request by gokh4nozturk**
Fix: Animated List

Pulled from issues: https://github.com/magicuidesign/magicui/issues/333

### CODE REVIEW

**Comment by gokh4nozturk** [comment]
> So what it does basically - stop the animation after all the items are shown?

Yes @itsarghyadas

**Comment by itsarghyadas** [comment]
@gokh4nozturk thanks for the reply. So if I’m understanding correctly, after displaying all the notifications for a set time, the animation just stops until you refresh the page. Is that correct?

Also, could you explain how this optimizes the functionality and what specific error you saw, as mentioned in the issue https://github.com/magicuidesign/magicui/issues/333

**Comment by itsarghyadas** [comment]
Why do you think the animation stopping when the number of elements runs out is expected? Just trying to understand your perspective.

**Comment by itsarghyadas** [comment]
We discussed this internally, and I’ve reviewed it. This PR is good to go. Thanks for the contribution!

**Pull request merged**
