### PR TITLE
Bug fixes: Fixes #78 & #81

### LINKED ISSUE #78: Having a declared packageManager in the package.json is creating issues with other versions of pnpm.
packageManager

pnpm-version-error

Is it necessary to declare the `packageManager` version in the `package.json`? If I have a different version of `pnpm` installed on my system, it causes an error. I believe we can remove this or make it less restrictive. Let me know your thoughts @dillionverma

### LINKED ISSUE #81: Contentlayer warning on Windows - Warning: Contentlayer might not work as expected on Windows
After downgrading my Node version to v18 from v20 in order to make the content layer dependency to work, but weirdly it prompts a warning whenever I run the `pnpm dev` command. Here is what happens:

 
WARN  Unsupported engine: wanted: {"node":">=20.6.1"} (current: {"node":"v18.17.0","pnpm":"9.0.4"})

> magicui@0.1.1 dev C:\Users\USER\Documents\Programming\open-source\magicui
> next dev

   ▲ Next.js 14.1.0
   - Local:        http://localhost:3000
   - Environments: .env.local
   - Experiments (use at your own risk):
     · optimizeCss

Warning: Contentlayer might not work as expected on Windows
 ✓ Ready in 63.8s
Contentlayer config change detected. Updating type definitions and data...
Warning: Found 23 problems in 49 documents.

 └── 23 documents contain field data which didn't match the structure defined in the document type definition. (Skipping documents)

     • "docs/changelog.mdx" of type "Doc" has the following incompatible fields:       
       • published: "false\r"
     • "docs/installation.mdx" of type "Doc" has the following incompatible fields:    
       • published: "true\r"
     • "docs/story.mdx" of type "Doc" has the following incompatible fields:
       • published: "false\r"
     • "docs/components/animated-grid-pattern.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/animated-list.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/avatar-circles.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/bento-grid.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/blur-in.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/box-reveal.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/fade-text.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/flip-text.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/gradual-spacing.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/icon-cloud.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/letter-pullup.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/scroll-based-velocity.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/separate-away.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/shine-border.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/shiny-button.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/typing-animation.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • "docs/components/wavy-text.mdx" of type "Doc" has the following incompatible fields:
       • published: "true\r"
     • ... 3 more documents (Use the --verbose CLI option to show all documents)      

Generated 26 documents in .contentlayer

Can someone please suggest a fix to this?

### PR DESCRIPTION
**Pull request by BankkRoll**
### Changed
- Updated PNPM version requirement in `package.json` from `>=9` to `>=8` to support a wider range of PNPM versions, while still recommending PNPM version 9.0.4. Fixes #78

### Added
- Added `.gitattributes` file to ensure consistent line endings across different operating systems. This should help avoid issues related to line ending differences when working on various os. Fixes #81

### CODE REVIEW

**Comment by itsarghyadas** [comment]
@BankkRoll does this fix the issue? I think the error is caused by this line: `"packageManager": "pnpm@9.0.4"`. Until you use this specific version of pnpm, it will cause this error. Can you confirm if it works?

Thanks,
Arghya

**Comment by BankkRoll** [comment]
Hey @itsarghyadas can confirm it worked on my end.. - Windows

This is only the suggested version
```
"packageManager": "pnpm@9.0.4"
```
 
This is the required minimum versions
```
  "engines": {
    "node": ">=20.6.1",
    "pnpm": ">=8"
  },
  ```

**Comment by dillionverma** [comment]
this is amaszing! Thanks so much for setting this up

any idea why the pnpm lockfile version is now 6.0?

image

I also noticed a lot of the package versions across the board were bumped down to older versions. Any idea why?

**Comment by dillionverma** [comment]
Looks like rolling back the package versions caused build to fail :( 
image

**Comment by BankkRoll** [comment]
> this is amaszing! Thanks so much for setting this up
> 
> any idea why the pnpm lockfile version is now 6.0?
> 
> image
> 
> I also noticed a lot of the package versions across the board were bumped down to older versions. Any idea why?

Hey @dillionverma i'll look some more into this tonight or tomorrow, sorry for the delay. Was out of town for holiday. I only changed the required version of pnpm, didnt downgrade any other package versions just added the new lock file as wouldn't build correctly without.. ill do some more research here tonight and try to get it fully compatible.

---

> Looks like rolling back the package versions caused build to fail :( image

Will also look into this as well while doing so to make sure again its fully compatible. Will ping you back here to test as once i check it out 🤛

**Comment by BankkRoll** [comment]
The type error that UnistTree is not compatible with Node<Data> due to the missing type property should be fixed, UnistTree tree needs to extend UnistNode to fix type error. 

---

> Looks like rolling back the package versions caused build to fail :( image

Cannot build myself as there is no prisma schema to generate and test build. If you can try and let me know! Will hop in discord maybe we can connect there easier!

**Comment by dillionverma** [comment]
tysm for this!!

i was trying to merge it in but the conflicts were messing me up a bit

i just ended up adding the changes directly to main!!

Tysm for surfacing this to the community and myself 🙏

https://github.com/magicuidesign/magicui/commit/37bc4adb244f18f0042ef3f3d27db23ef21900be

**Comment by dillionverma** [comment]
closing for now

**Pull request closed without merging**
