### PR TITLE
Refactor TableOfContents component and improve rendering efficiency

### PR DESCRIPTION
**Pull request by gokh4nozturk**
This pull request refactors the TableOfContents component to improve rendering efficiency. It also includes a refinement to the DashboardTableOfContents component to include links in steps. These changes optimize the performance of the code and enhance the user experience.

adresses: https://github.com/magicuidesign/magicui/issues/96

### CODE REVIEW

**Comment by gokh4nozturk** [comment]
localhost_3000 · 7 09pm · 06-03
localhost_3000

**Comment by safethecode** [comment]
sounds good :)

**Comment by gokh4nozturk** [comment]
> sounds good :)

thanks your contributions 🤘🏻

**Review by safethecode — APPROVED** [review]

**Review by dillionverma — APPROVED** [review]
very smart solution btw love it 🔥

LGTMM

**Pull request merged**
